# Generated by Django 5.1.5 on 2025-01-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('drinks', 'Напитки'), ('main', 'Основные блюда'), ('desserts', 'Десерты')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидается'), ('in progress', 'В процессе'), ('finish', 'Завершён')], default='new', max_length=20),
        ),
    ]
